version: '3'

services:
  app:
    image: "ghcr.io/tonyc/open890:latest"
    ports:
      - "4000:4000"
      - "60001:60001/udp"
    volumes:
      - "./open890-db:/app/db"
      - "./open890-config:/app/config"
    environment:
      # change the following line if you run into the "check_origin" issue or need to otherwise change the hostname open890 listens for
      - "OPEN890_HOST=localhost"

