# open890 default configuration
#
# Copy this file to config/config.toml and make your changes.
# This is a TOML file: https://toml.io/en/

# required - don't change this unless instructed otherwise!
version = "1.0.0"

# Enable a username/password to access the web server.
# This is completely separate from any KNS usernam you may set up
# for a connection to a radio.
#
# Note that this does NOT mean the connection is encrypted in any way,
# and only serves as a basic means to secure access to open890/your radio.
#
# The most secure option is to run open890 behind a VPN if accessing
# it remotely.
#
# DO NOT ENABLE THIS WITHOUT CHANGING THE DEFAULT USERNAME AND PASSWORD!
[http.server.auth]
enabled = false
http_basic_username = "CHANGE_ME_TO_SOMETHING_SECURE"
http_basic_password = "ALSO_CHANGE_ME_TO_SOMETHING_SECURE"


# Define your macros here.
# Each macro will be displayed in order as a clickable button in the UI.
#
# "label" is the text that will appear on the button.
#
# "commands" is an array strings of CAT commands to send to the radio with a 100ms delay.
# You do not need to terminate them with a semicolon (see the examples below).
#
# The TS-890 command reference is available at:
# https://www.kenwood.com/i/products/info/amateur/pdf/ts890_pc_command_en_rev1.pdf
#
# One special command is implemented:
#
# DEnnn
# DElay the next command by (nnn * 10) milliseconds, where nnn is 0 ... 255
#
# The general format is:
#
# [[ui.macros]]
# label = "Button name"
# commands = [
#   "CMD1",
#   "CMD2",
# ]
#
# [[ui.macros]]
# label = "Another Button"
# commands = [
#   "CMD3",
#   "CMD4",
# ]

[[ui.macros]]
label = "40m SKCC CW"
commands = [
  "FR0",
  "FA00007055000",
  "DE100",
  "OM07",
  "BS32",
  "DE100",
  "BS43",
  "DE100",
  "FL00",
  "SL009",
  "SH0080"
]

[[ui.macros]]
label = "20m FT8"
commands = [
  "FR0",            # VFO A
  "FA00014074000",  # VFO A freq
  "DE100",          # DELAY 1000ms
  "BS32",           # auto-scroll mode
  "BS40",           # bandscope span 5 khz
  "BSE",            # bandscope shift
  "BSK2",           # bandscope shift -2
  "OM02",           # USB
  "SL000",          # low cut 0 hz
  "SH0024",         # hi cut 3000 hz
  "FL00",           # FIL A
  "NR0",            # NR off
]
