name: Build Open890 with Marker Buttons

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          ref: v.1.2.0-fork

      - name: Apply marker-buttons patch
        run: |
          echo "Applying marker buttons patch..."
          git apply .github/patches/marker-buttons.patch

      - name: Setup Elixir and Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.15.7'
          otp-version: '26.2'

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies and build assets
        run: |
          mix deps.get
          cd assets
          npm ci
          npm run deploy
          cd ..
          mix assets.deploy

      - name: Compile & release
        run: |
          MIX_ENV=prod mix compile --force
          MIX_ENV=prod mix release

      - name: Package release
        run: |
          cd _build/prod/rel
          zip -r open890-marker-buttons.zip open890
          mv open890-marker-buttons.zip $GITHUB_WORKSPACE/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: open890-marker-buttons
          path: open890-marker-buttons.zip
